version: "3"

services:
  server:
    build: server/
    command: python3 ./server.py
    ports:
      - 20002:20000
  client:
    build: client/
    command: python3 ./client.py
    network_mode: host
    depends_on:
      - server
